Gui list
RUGSoftEng/2017-Hestia-Client pull request #1
Opened 2017-03-07 13:05 UTC by markhelmus

2017-03-07 14:51 UTC, FrankTN commented
You should probably remove the .idea files and update the .gitignore to prevent the project from getting messy

2017-03-07 15:39 UTC, FrankTN requested changes
In general, this looks good. There are a lot of hardcoded things which need to change at a later stage.

My main concern is with the JSON specification, which does not agree completely with the one published on Basecamp.

I also recommend adding comments in critical sections, to increase readability.

2017-03-07 15:39 UTC, FrankTN commented on Hestia/app/src/main/java/com/rugged/application/hestia/Client.java
> +        this.writeJSONToServer(jsonObj);
This should comply with the JSON object as defined on basecamp, so:
`
{
  "action": {
    "id": 1,
    "type": "Lock"
  }
}
`

2017-03-07 17:14 UTC, suzannemaquelin requested changes
I think you made a mistake with "openLock". For the off button it should be closeLock

2017-03-07 17:14 UTC, suzannemaquelin commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralFragment.java
> +                new SendJSONFile2().execute("82.73.173.179", "openLock");
For the off button, shouldn't it be "closeLock"?

2017-03-07 17:14 UTC, suzannemaquelin commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralLab.java
> +public class PeripheralLab {
It's probably just me, but I don't understand what peripheralLab and sPeripheralLab are

2017-03-08 10:14 UTC, Feikoritsema approved these changes
It seems weird to review my own code, I read through it once more and approve.

2017-03-08 11:03 UTC, FrankTN approved these changes

2017-03-08 11:04 UTC, FrankTN commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralLab.java
> +public class PeripheralLab {
I had the same thing, its probably a good idea to add some comments in these parts.

2017-03-08 11:43 UTC, markhelmus commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralLab.java
> +public class PeripheralLab {
I added some explaining comments. Hopefully it is understandable what those classes are doing. If not, please let me know.

2017-03-08 11:59 UTC, suzannemaquelin approved these changes

2017-03-08 12:02 UTC, merged