Feature/required info description
RUGSoftEng/2017-Hestia-Client pull request #122
Opened 2017-05-27 13:42 UTC by markhelmus

Note that app crashes if this.serverCollectionsInteractor.getHandler().getIp() is null (in IpDialog, line 32)

2017-05-27 14:14 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/UI/dialogs/AddDeviceInfo.java
> +                    AlertDialog dialog = builder.create();
not very important, but we could rearrange this part

2017-05-27 14:16 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/UI/dialogs/HestiaDialog.java
> +
Is this part still needed, otherwise, remove it

2017-05-27 14:17 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/UI/dialogs/HestiaDialog.java
> +
You don't need this switch statement anymore, do you?

2017-05-27 14:19 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/UI/dialogs/IpDialog.java
> +
I suggest we create a new method that checks the entered ip address. Such a check would include the following:
- ip is not null, nor is it empty.
- should contain only numbers.
- should have the correct formating of an ip (v4/v6, groups of numbers not greater than 255)

2017-05-27 14:21 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/UI/dialogs/HestiaDialog.java
> +        //TODO: better code
Finish the TODO first, then remove it

2017-05-27 14:23 UTC, StefanEvanghelides requested changes
Interesting change from Dialog to AlertDialog. I added separate comments to parts that could be improved.
Don' forget to add comments to these clases

2017-05-27 17:42 UTC, Feikoritsema commented on Hestia/app/src/main/java/hestia/UI/dialogs/IpDialog.java
> +
Check my ip branch pull request for How to use Java Patterns (regex) to check this. If I have the time today i Will add it.

2017-05-28 13:47 UTC, StefanEvanghelides commented
Tests still fail; Merge conflics

2017-05-28 19:41 UTC, LarsHoldijk requested changes
Need to wait for Mark his changes with the dialog

2017-05-29 18:58 UTC, closed without merging