Exceptions
RUGSoftEng/2017-Hestia-Client pull request #129
Opened 2017-05-28 14:14 UTC by ChrisAusema

added all the exceptions

2017-05-28 14:16 UTC, Feikoritsema requested changes
Overall looks fine, but some redundant white lines and comments at the top which are not needed.

2017-05-28 14:16 UTC, Feikoritsema commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/CollectionNotFoundException.java
> +
Redundant white lines

2017-05-28 14:16 UTC, Feikoritsema commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/PluginNotFoundException.java
> + * Created by chris on 28-5-2017.
Not really needed + white lines

2017-05-28 14:16 UTC, Feikoritsema commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/ServerException.java
> +
Again

2017-05-28 14:16 UTC, Feikoritsema commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/UndefinedServerException.java
> + * Created by chris on 28-5-2017.
Same

2017-05-28 14:25 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/UndefinedServerException.java
> + * Created by chris on 28-5-2017.
You can also delete the "Created by chris..."

2017-05-28 14:28 UTC, StefanEvanghelides approved these changes

2017-05-28 16:06 UTC, StefanEvanghelides approved these changes

2017-05-28 16:07 UTC, StefanEvanghelides requested changes
Some exceptions are randomly thrown

2017-05-28 19:37 UTC, LarsHoldijk requested changes
There was nothing done with the Undefined Server Exceptions. These need to be thrown.

2017-05-28 19:37 UTC, LarsHoldijk commented on Hestia/app/src/main/java/hestia/backend/ServerCollectionsInteractor.java
> +            throw new DeviceNotFoundException(error, message);
The payload not being a json array does not mean that the device is not founf.

2017-05-28 19:37 UTC, LarsHoldijk commented on Hestia/app/src/main/java/hestia/backend/ServerCollectionsInteractor.java
> +                throw new DeviceNotFoundException(error, message);
The payload containing a error does not mean that the device was not found

2017-05-28 19:37 UTC, LarsHoldijk commented on Hestia/app/src/main/java/hestia/backend/ServerCollectionsInteractor.java
> +                throw new DeviceNotFoundException(error, message);
Same

2017-05-28 19:37 UTC, LarsHoldijk commented on Hestia/app/src/main/java/hestia/backend/ServerCollectionsInteractor.java
> +                throw new DeviceNotFoundException(error, message);
Same

2017-05-28 19:37 UTC, LarsHoldijk commented on Hestia/app/src/main/java/hestia/backend/ServerCollectionsInteractor.java
> +            throw deviceNotFoundException;
Same

2017-05-28 19:37 UTC, LarsHoldijk commented on Hestia/app/src/main/java/hestia/backend/models/Activator.java
> +                throw new DeviceNotFoundException(error, message);
Same

2017-05-28 19:37 UTC, LarsHoldijk commented on Hestia/app/src/main/java/hestia/backend/models/Device.java
> +            throw deviceNotFoundException;
Same

2017-05-28 22:38 UTC, FrankTN requested changes
The code in its current state is not building on Travis, try running it locally to find the problems. Once they are resolved, run the tests locally and then push. In this case you can be fairly certain that the build will pass Travis.

2017-05-29 18:59 UTC, closed without merging

2017-05-29 18:59 UTC, StefanEvanghelides commented
I suggest we close this pull request. Will fix this part during the next sprint