Test backendtests
RUGSoftEng/2017-Hestia-Client pull request #134
Opened 2017-05-31 13:29 UTC by StefanEvanghelides

Preparing the pull request  early. Before merging, every backend class must be tested. We should easily achieve 80-90% coverage level in this package.

2017-05-31 15:38 UTC, FrankTN requested changes
Nice refactoring of some earlier classes and good to see some new tests. Unfortunately, some tests still expect ComFaultExceptions. This needs to be changed otherwise it will not build

2017-05-31 15:38 UTC, FrankTN commented on Hestia/app/src/androidTest/java/com/rugged/application/hestia/backend/NetworkHandlerTest.java
> +        assertTrue(dummyHandler.isSuccessfulRequest(responseCodeSuccess));
Nice!

2017-06-01 18:25 UTC, StefanEvanghelides commented
TODO's:
- Improve Activator tests
- Tests for all deserializers.
- Check coverage levels for each class, see how I can improve them

2017-06-03 09:25 UTC, LarsHoldijk requested changes
Really impressive work Stefan. I just had some minor things that have to do with the structure of the tests. To make it more readable and easier to see what failed we could divide the tests. Some have at the moment different sections where different scenarios are tested.

Btw, mocking the network handler with mockito looks really good. Nice find!

2017-06-03 09:25 UTC, LarsHoldijk commented on Hestia/app/src/androidTest/java/com/rugged/application/hestia/backend/NetworkHandlerTest.java
>      }
This could  be divided into multiple methods, this makes it easier to see which assert fails.

2017-06-03 09:25 UTC, LarsHoldijk commented on Hestia/app/src/androidTest/java/com/rugged/application/hestia/backend/models/ActivatorStateTest.java
> +    }
Instead of indication the different sections it would be better to divide them evenly.

2017-06-03 12:32 UTC, FrankTN approved these changes

2017-06-04 11:08 UTC, LarsHoldijk approved these changes

2017-06-04 11:09 UTC, merged