Test dialogTests
RUGSoftEng/2017-Hestia-Client pull request #135
Opened 2017-06-01 12:03 UTC by Feikoritsema

At least every dialog should be tested before merging this. Early pull request too.

2017-06-06 16:42 UTC, StefanEvanghelides commented on Hestia/app/src/androidTest/java/com/rugged/application/hestia/UI/activities/login/LoginTest.java
> +                .perform(typeText(PASSWORD), closeSoftKeyboard());
why not on the same line?

2017-06-06 16:43 UTC, StefanEvanghelides commented on Hestia/app/src/androidTest/java/com/rugged/application/hestia/UI/dialogs/IpDialogTest.java
> +        onView(withText("Confirm")).perform(click());
hmm, I believe you should use the resources here. Or is there a reason not to? If the text on the buttons is hard-coded, then it should be fixed as well.

2017-06-06 16:43 UTC, StefanEvanghelides commented on Hestia/app/src/androidTest/java/com/rugged/application/hestia/UI/dialogs/SlideDialogTest.java
> +//}
Commented out code.

2017-06-06 16:54 UTC, LarsHoldijk commented on Hestia/app/src/androidTest/java/com/rugged/application/hestia/UI/dialogs/IpDialogTest.java
> +        onView(withText("Confirm")).perform(click());
This is part of how AlertDialogs work, this was the best solution to test this

2017-06-07 07:06 UTC, Feikoritsema commented on Hestia/app/src/androidTest/java/com/rugged/application/hestia/UI/dialogs/SlideDialogTest.java
> +//}
yeah It's not meant to be merged yet, will fix this

2017-06-07 07:07 UTC, Feikoritsema commented on Hestia/app/src/androidTest/java/com/rugged/application/hestia/UI/activities/login/LoginTest.java
> +                .perform(typeText(PASSWORD), closeSoftKeyboard());
Because it exceeds that grey line, which you shouldn't pass right?

2017-06-07 07:08 UTC, StefanEvanghelides commented on Hestia/app/src/androidTest/java/com/rugged/application/hestia/UI/activities/login/LoginTest.java
> +                .perform(typeText(PASSWORD), closeSoftKeyboard());
yeah, didn't check it, though it would fit it :)

2017-06-09 11:03 UTC, FrankTN requested changes
Looks good, I think this can be merged if we remove the commented code.

2017-06-09 11:03 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/UI/activities/home/DeviceListFragment.java
> +    //TODO: Check whether this works with a server
Commented code should not enter development anymore. I suggest fixing this or removing it altogether.

2017-06-09 11:03 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/UI/activities/home/HomeActivity.java
> +        //TODO: Check whether this works with a server
Same here

2017-06-09 11:03 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/UI/dialogs/ChangeIpDialog.java
> +    private static final String IPADDRESS_PATTERN = "^([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\." +
Nice! Using regexes to verify IP's

2017-06-09 11:03 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/UI/dialogs/ChangeNameDialog.java
> +        return getString(R.string.changeNameTitle);
Good job replacing the strings in the tests with references to the XML.

2017-06-11 18:30 UTC, closed without merging