all the defined exceptions have been added
RUGSoftEng/2017-Hestia-Client pull request #136
Opened 2017-06-03 10:37 UTC by ChrisAusema

added the exeption classes.

2017-06-03 12:31 UTC, FrankTN requested changes
The idea here is nice but it needs some improvement. Is there also code which handles this in the frontend? If not, can you look into this or discuss it with the frontend team? Similarly, the Exceptions don't all have an error and a message, some have only an error or only a message. Can you discuss this with the server team so that every exception has both? That makes handling these exceptions much nicer, especially if they all extend from some abstract superclass, for instance HestiaException.

2017-06-03 12:31 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/InvallidStateException.java
> +public class InvallidStateException extends DefinedServerException {
Minor spelling error, should be InvalidStateException, please refactor.

2017-06-03 12:31 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/ServerException.java
> +public abstract class ServerException extends Exception {
I think the naming should be changed, ServerException and DefinedServerException sound too similar, but they represent completely different problems. DefinedServerException sounds like it is a subclass of ServerException.

2017-06-03 12:31 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/UndefinedServerException.java
> +public class UndefinedServerException extends ServerException {
Also I think its strange that a DefinedServerException extends Exception but an UndefinedServerException extends ServerException. This asymmetry is not desirable.

2017-06-03 12:59 UTC, ChrisAusema commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/ServerException.java
> +public abstract class ServerException extends Exception {
oh my bad, must have been an error while importing these classes, definedServerException should indeed have indeed inherrited from serverExeption, will fix this

2017-06-04 09:39 UTC, StefanEvanghelides requested changes
I would also suggest adding tests for them. The tests themselves are fairly easy: 2 tests to test the getters and setters of the 2 fields.

2017-06-09 20:54 UTC, LarsHoldijk requested changes
Few changes:
- Don't pass in the jsonObjects this spreads the dependency on gson which makes it harder to change the frontend.
- Fix the strange empty lines in the wrong location
- There is something stange going on with overriding getMessage when the base class doesn't appear to have those.
- Testing seems to be very minimal, talk with Stefan about whether or not this is sufficient. 
- Tests can be split into different ones for every assert.

2017-06-09 20:54 UTC, LarsHoldijk commented on Hestia/app/src/androidTest/java/com/rugged/application/hestia/backend/exceptions/ServerExceptions/DataBaseExceptionTest.java
> +
Formatting, empty line before the } instead of after

2017-06-09 20:54 UTC, LarsHoldijk commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/ServerException.java
> +    }
Exceptions comming from the server no longer always have a message field. This was discussed last sunday.

2017-06-09 20:54 UTC, LarsHoldijk commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/DatabaseException.java
> +    }
See comment at ServerException. Override shouldn't be needed when the comment there is fixed.

2017-06-09 20:54 UTC, LarsHoldijk commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/SetupFailedException.java
> +    public SetupFailedException(String error, JsonObject details){
Pass in the fields as separate parameters. This spreads the dependency on gson.

2017-06-09 21:07 UTC, StefanEvanghelides commented on Hestia/app/src/androidTest/java/com/rugged/application/hestia/backend/exceptions/ServerExceptions/undefinedServerExceptionTest.java
> +public class undefinedServerExceptionTest {
A class should start with capital letter

2017-06-10 11:16 UTC, ChrisAusema commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/ServerException.java
> +    }
renamed it to error.

2017-06-10 11:16 UTC, ChrisAusema commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/DatabaseException.java
> +    }
removed it,it was a overide of a Exception method.

2017-06-10 11:17 UTC, ChrisAusema commented on Hestia/app/src/main/java/hestia/backend/exceptions/ServerExceptions/SetupFailedException.java
> +    public SetupFailedException(String error, JsonObject details){
don't think i get what you mean, Gson is not used in the parsing of the informationn right?

2017-06-10 11:18 UTC, ChrisAusema commented on Hestia/app/src/androidTest/java/com/rugged/application/hestia/backend/exceptions/ServerExceptions/undefinedServerExceptionTest.java
> +public class undefinedServerExceptionTest {
refactored it

2017-06-10 13:25 UTC, closed without merging