Refactor/harcoded strings
RUGSoftEng/2017-Hestia-Client pull request #146
Opened 2017-06-10 20:04 UTC by ChrisAusema

The Harcoded Strings are now called from withing the string.xml file

2017-06-10 21:00 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/UI/dialogs/AddDeviceDialog.java
> +        return getContext().getString(R.string.addDeviceTitle);
This quite a strange name for a dialog. I believe that simply "Add device" should do.

2017-06-10 21:00 UTC, StefanEvanghelides commented on Hestia/app/src/main/res/values/strings.xml
> +    <string name="addDeviceTitle">new Add device</string>
As stated earlier, "new Add device" is quite a strange name for a dialog. Simply "Add device" should do in my opinion

2017-06-10 21:03 UTC, StefanEvanghelides commented
Good changes. Well done Chris.

2017-06-11 09:13 UTC, LarsHoldijk requested changes
To be honest I dont think having all string in one big file is helpfull. It is quite easy to make seperate string files for every class.

2017-06-11 09:13 UTC, LarsHoldijk commented on Hestia/app/src/main/java/hestia/UI/dialogs/AddDeviceDialog.java
> +        return getContext().getString(R.string.addDeviceTitle);
This is my mistake. I changed the name to " new Add device" to see whether or not the dialog actually changed. Forgot to change it back.

2017-06-12 16:24 UTC, closed without merging