Release 0.1
RUGSoftEng/2017-Hestia-Client pull request #3
Opened 2017-03-09 12:20 UTC by FrankTN

Clientside code for Hestia release 0.1

2017-03-10 12:54 UTC, LucvandenBrand requested changes
**Allot** of redundant white-spaces! Makes your code look very messy...
Use proper documentation comments for each class.
Peripheral fragment's and associated classes seem to be hard-coded and not generic enough. Making it extendable is important, especially in your case.
For more info, check the specific comments.
In the future, try to use the issue system.

2017-03-10 12:54 UTC, LucvandenBrand commented on Hestia/app/build.gradle
> +        minSdkVersion 15
Just a simple question: have you discussed the min and target version with the customer? If you are able to target a newer version as minimum, that's always easier to develop ;)

2017-03-10 12:54 UTC, LucvandenBrand commented on Hestia/app/src/main/AndroidManifest.xml
> +
Redundant white space. Happens in most of your files.

2017-03-10 12:54 UTC, LucvandenBrand commented on Hestia/app/src/main/java/com/rugged/application/hestia/Client.java
> + * TODO: Find best options for Input and Output.
Todo's should have an associated issue on github.

2017-03-10 12:54 UTC, LucvandenBrand commented on Hestia/app/src/main/java/com/rugged/application/hestia/Client.java
> +            e.printStackTrace();
Use your logger in catch statements to log errors.

2017-03-10 12:54 UTC, LucvandenBrand commented on Hestia/app/src/main/java/com/rugged/application/hestia/Client.java
> +            Log.i(TAG, jsonObj.toJSONString());
Make your log message more specific. Such as "Sending json: <JSONOBJ>" or equivalent.

2017-03-10 12:54 UTC, LucvandenBrand commented on Hestia/app/src/main/java/com/rugged/application/hestia/Client.java
> +package com.rugged.application.hestia; /**
Add a short but descriptive documentation comment that explains what the class does in abstract.
[Javadoc tutorial](http://www.oracle.com/technetwork/articles/java/index-137868.html)
Also do this for method definitions (not necessarily needed for completely obvious methods like getters and setters).
**This goes for most if not all of your classes.**

2017-03-10 12:54 UTC, LucvandenBrand commented on Hestia/app/src/main/java/com/rugged/application/hestia/Peripheral.java
> +
Trailing white spaces.

2017-03-10 12:54 UTC, Lukeslux commented on Hestia/app/src/main/java/com/rugged/application/hestia/Peripheral.java
> +    private UUID uuId;
Documentation comments would be especially useful in this file, as it is somewhat confusing to have two different types of identifier variables. I suppose you use UUID for your serializing? What is the use of id though?

2017-03-10 12:54 UTC, Lukeslux commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralFragment.java
> +    @Override
Missing white space.

2017-03-10 12:54 UTC, Lukeslux commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralFragment.java
> +        switch (mPeripheral.getType()) {
Should be done in a flexible OOP manner, such as inheritance or a Design Pattern. This switch case is rather ugly and will only give you trouble later in development.

2017-03-10 12:54 UTC, Lukeslux commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralFragment.java
> +                onButton.setText("Lock");
Use the android string constant file for constant strings. Makes the code cleaner and will help you with multiple language support in the future (just one xml file to translate).

2017-03-10 12:54 UTC, Lukeslux commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralFragment.java
> +                new SendJSONFile().execute("82.73.173.179", "openLock");
Hard-coded constants, which you seem to use in most of the file.
Quoting the Clean Code cheat sheet:
> Replace Magic Numbers and Strings with named constants to give them a
meaningful name when meaning cannot be derived from the value itself.

You seem to have hard-coded the fact that this is a lock peripheral as well?

2017-03-10 12:54 UTC, Lukeslux commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralFragment.java
> +    private class SendJSONFile2 extends AsyncTask<String,Void,Void> {
Bad naming and redundant code.

2017-03-10 12:54 UTC, Lukeslux commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralLab.java
> +    private PeripheralLab(Context context) {
context is never used.

2017-03-10 12:54 UTC, Lukeslux commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralFragment.java
> +        int peripheralId = (int) getActivity().getIntent()
Why not simply pass the object in the intent?

2017-03-10 12:54 UTC, Lukeslux commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralLab.java
> +    private List<Peripheral> mPeripherals;
If you link IDs to objects, why not use a hashtable?

2017-03-10 12:54 UTC, Lukeslux commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralListFragment.java
> +package com.rugged.application.hestia;
This class will specially benefit from cleanup and documentation. Unpleasant to parse otherwise.

2017-03-10 12:54 UTC, Lukeslux commented on Hestia/app/src/main/res/values/strings.xml
> +<resources>
This is the string constants file I was referring to.

2017-03-10 12:54 UTC, Lukeslux commented on Hestia/app/src/test/java/com/rugged/application/hestia/ExampleUnitTest.java
> +public class ExampleUnitTest {
No need for this in your repository.

2017-03-14 11:19 UTC, Feikoritsema commented on Hestia/app/build.gradle
> +        minSdkVersion 15
Yes we have discussed this, this is fine.

2017-03-16 20:07 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/com/rugged/application/hestia/Client.java
> + * TODO: Find best options for Input and Output.
Will keep that in mind. Right now this TODO is no longer valid.

2017-03-21 12:09 UTC, Feikoritsema commented on Hestia/app/src/main/java/com/rugged/application/hestia/Client.java
> +package com.rugged.application.hestia; /**
The javadoc will be done a lot better for the next release. But for this release, creating the javadoc is not really relevant anymore, as all code has changed. Is this ok?

2017-03-21 12:18 UTC, Feikoritsema commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralFragment.java
> +        int peripheralId = (int) getActivity().getIntent()
Fixed in next release. Will use putExtra() and getExtra().

2017-03-21 12:21 UTC, Feikoritsema commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralFragment.java
> +        switch (mPeripheral.getType()) {
Already fixed for next release.

2017-03-21 12:23 UTC, Feikoritsema commented on Hestia/app/src/main/res/values/strings.xml
> +<resources>
Using it now.

2017-03-21 12:25 UTC, Feikoritsema commented on Hestia/app/src/main/java/com/rugged/application/hestia/PeripheralLab.java
> +    private List<Peripheral> mPeripherals;
Good idea, will use a hashtable.

2017-03-21 12:26 UTC, Feikoritsema commented
A lot of the big code changes you suggested will be done in the next release.
The javadoc and whitespaces will of course be kept in mind, and properly fixed.

2017-03-21 17:27 UTC, LucvandenBrand approved these changes
Acceptable, on the promise of an improved iteration.

2017-03-21 17:27 UTC, Lukeslux commented on Hestia/app/src/main/java/com/rugged/application/hestia/Client.java
> +package com.rugged.application.hestia; /**
Yes. This is ok.

2017-03-21 17:29 UTC, merged