Refactoring tasks
RUGSoftEng/2017-Hestia-Client pull request #62
Opened 2017-05-06 15:17 UTC by StefanEvanghelides

Refactored AsyncTasks, which can be found in the "requests" package, under "backend".

Architecture:
- Request - super class, which contains data for connecting to the Server
- DeleteRequest - subclass of Request. Does a DELETE request
- PostRequest - subclass of Request. Does a DELETE request. It is used for both Adding a new device and change the current state of a device.
- GetRequest - an abstract class, subclass of Request.
- GetDevicesRequest - subclass of GetRequest. Will be used to do a GET request for the list of devices.
- GetPluginInformationRequest - subclass of GetRequest. Will be used to do a GET request for the relevant information of the Plugin.

Unless it is fixed in the Merging Conflicts, this may cause again problems with the Sliders.

2017-05-07 14:43 UTC, FrankTN requested changes
Looks very nice. We will need to change the Request type from <T> to a JSON object, since we know that this is always returned.

2017-05-07 14:43 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/UI/AddDeviceInfo.java
> +                String path = BackendInteractor.getInstance().getPath() + "devices/";
We need to change all of these path references, but this is not an issue of the current PR, I just wanted to mention it here as well.

2017-05-07 14:43 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/UI/AddDeviceInfo.java
> +            if("".equals(valueField)) {
Make an empty string constant for this. "" is a bit weird.

2017-05-07 14:43 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/UIWidgets/HestiaSwitch.java
>      private Switch activatorSwitch;
Good job on removing all the single letter variables

2017-05-07 14:43 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/UIWidgets/HestiaSwitch.java
> +    public void onCheckedChanged(CompoundButton compoundButton, boolean bool) {
Boolean bool needs a better name still which should encode its meaning.

2017-05-07 14:43 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/UIWidgets/HestiaSwitch.java
> +        //int activatorId = a.getId();
This can be removed completely.

2017-05-07 14:43 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/backend/BackendInteractor.java
> +        String path = this.getPath() + "devices/" + id;
Same problem here with the strings

2017-05-07 14:43 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/backend/requests/GetPluginInformationRequest.java
> +    protected Type getReturnType() {
We don't need this, the getRequest should always return a JSON object.

2017-05-07 14:43 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/backend/requests/GetDevicesRequest.java
> +public class GetDevicesRequest extends GetRequest<ArrayList<Device>> {
This should return a JSON object, the caller will know it is a list of devices.

2017-05-07 14:43 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/backend/requests/GetRequest.java
> +abstract class GetRequest<T> extends Request {
We can change T into a JSON object, we know that we will always get a JSON object.

2017-05-07 14:53 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/UI/AddDeviceInfo.java
> +            if("".equals(valueField)) {
done.

2017-05-07 15:17 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/UIWidgets/HestiaSwitch.java
> +    public void onCheckedChanged(CompoundButton compoundButton, boolean bool) {
done. Also refactored the whole class.

2017-05-07 15:17 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/UIWidgets/HestiaSwitch.java
> +        //int activatorId = a.getId();
done.

2017-05-07 15:27 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/UI/AddDeviceInfo.java
> +    private final String EMPTY_STRING="";
I think it can be static as well.

2017-05-07 19:06 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/backend/requests/GetPluginInformationRequest.java
> +    protected Type getReturnType() {
True, will fix this in the upcoming days

2017-05-08 22:24 UTC, FrankTN commented
I suggest we merge this as it contains a lot of really nice refactoring. We will still have to change the getRequests so they return JSON objects, I will create an issue for this (this is not really refactoring anyways, since it changes the underlying functionality, so it shouldn't be on this branch).

2017-05-08 22:24 UTC, FrankTN approved these changes

2017-05-08 22:25 UTC, merged