Split BackendInteractor in 2 classes: Cache and BackendInteractor
RUGSoftEng/2017-Hestia-Client pull request #99
Opened 2017-05-18 14:50 UTC by StefanEvanghelides

Cache class will hold information about the list of devices, stored ip and port number, listeners to devices etc. Will act as a memory that will be updated by the BackendInteractor, after HTTP Requests.

BackendInteractor class will only take care of sending and receiving data from the server, updating the Cache when needed.

2017-05-18 20:26 UTC, StefanEvanghelides commented
Last commit should increase the coverage level, at least above 50%.

2017-05-19 10:19 UTC, FrankTN commented
I will review this later today when I have more time.

2017-05-19 10:35 UTC, FrankTN requested changes
Very nice! I like the split of backendInteractor into two separate parts. I also really like the tests. I think we can remove the Singleton pattern from the NetworkHandler, as it contains no shared fields.

2017-05-19 10:35 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/backend/Cache.java
> +    /**
We should add Javadoc to this to explain that it contains the devices and methods to access them.

2017-05-19 10:35 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/backend/Cache.java
> +    private Cache() {}
Maybe add a line here as well to explain why we need a private default constructor

2017-05-19 10:35 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/backend/NetworkHandler.java
> +public class NetworkHandler extends Application{
I don' t think NetworkHandler has to be a singleton, as the only data it contains is in the Cache, which is already a singleton.

2017-05-19 10:35 UTC, FrankTN commented on Hestia/app/src/main/java/hestia/UI/SingleFragmentActivity.java
> +        if(cache.getIp() == null) {
In general, I think methods should never return null, as it contains no information. We should at some point change the getIp() method.

2017-05-19 18:04 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/backend/NetworkHandler.java
> +public class NetworkHandler extends Application{
In that case, we should make all the fields static. It may become uglier this way. Do you have any suggestions?

2017-05-19 18:04 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/backend/Cache.java
> +    private Cache() {}
will do so

2017-05-19 18:04 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/backend/Cache.java
> +    /**
done

2017-05-19 18:05 UTC, StefanEvanghelides commented on Hestia/app/src/main/java/hestia/UI/SingleFragmentActivity.java
> +        if(cache.getIp() == null) {
I don't like it either, but it can be used as a safety measure

2017-05-20 14:03 UTC, FrankTN approved these changes

2017-05-20 14:04 UTC, merged